// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pdistance_cpp
arma::mat pdistance_cpp(const arma::mat& Ar, const arma::mat& Br, const float& eta);
RcppExport SEXP _coFAST_pdistance_cpp(SEXP ArSEXP, SEXP BrSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ar(ArSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Br(BrSEXP);
    Rcpp::traits::input_parameter< const float& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(pdistance_cpp(Ar, Br, eta));
    return rcpp_result_gen;
END_RCPP
}
// gene_embed_cpp
arma::mat gene_embed_cpp(const arma::mat& X, const arma::mat& ce_cell);
RcppExport SEXP _coFAST_gene_embed_cpp(SEXP XSEXP, SEXP ce_cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ce_cell(ce_cellSEXP);
    rcpp_result_gen = Rcpp::wrap(gene_embed_cpp(X, ce_cell));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coFAST_pdistance_cpp", (DL_FUNC) &_coFAST_pdistance_cpp, 3},
    {"_coFAST_gene_embed_cpp", (DL_FUNC) &_coFAST_gene_embed_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_coFAST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
