# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdistance_cpp <- function(Ar, Br, eta = 1e-10) {
    .Call(`_coFAST_pdistance_cpp`, Ar, Br, eta)
}

gene_embed_cpp <- function(X, ce_cell) {
    .Call(`_coFAST_gene_embed_cpp`, X, ce_cell)
}

